name: snapchat_example
description: Demonstrates how to use the snapchat plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  path: ^1.6.2
  path_provider: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  snapchat:
    path: ../

flutter:

  uses-material-design: true
  assets:
   - assets/example_sticker.png